/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package v1alpha1

// DistccListerExpansion allows custom methods to be added to
// DistccLister.
type DistccListerExpansion interface{}

// DistccNamespaceListerExpansion allows custom methods to be added to
// DistccNamespaceLister.
type DistccNamespaceListerExpansion interface{}

// DistccClaimListerExpansion allows custom methods to be added to
// DistccClaimLister.
type DistccClaimListerExpansion interface{}

// DistccClaimNamespaceListerExpansion allows custom methods to be added to
// DistccClaimNamespaceLister.
type DistccClaimNamespaceListerExpansion interface{}

// DistccClientListerExpansion allows custom methods to be added to
// DistccClientLister.
type DistccClientListerExpansion interface{}

// DistccClientNamespaceListerExpansion allows custom methods to be added to
// DistccClientNamespaceLister.
type DistccClientNamespaceListerExpansion interface{}

// DistccClientClaimListerExpansion allows custom methods to be added to
// DistccClientClaimLister.
type DistccClientClaimListerExpansion interface{}

// DistccClientClaimNamespaceListerExpansion allows custom methods to be added to
// DistccClientClaimNamespaceLister.
type DistccClientClaimNamespaceListerExpansion interface{}
