// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mbrt/k8cc (interfaces: Deployer)

// Package mock_k8cc is a generated GoMock package.
package mock_k8cc

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	net "net"
	reflect "reflect"
)

// MockDeployer is a mock of Deployer interface
type MockDeployer struct {
	ctrl     *gomock.Controller
	recorder *MockDeployerMockRecorder
}

// MockDeployerMockRecorder is the mock recorder for MockDeployer
type MockDeployerMockRecorder struct {
	mock *MockDeployer
}

// NewMockDeployer creates a new mock instance
func NewMockDeployer(ctrl *gomock.Controller) *MockDeployer {
	mock := &MockDeployer{ctrl: ctrl}
	mock.recorder = &MockDeployerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDeployer) EXPECT() *MockDeployerMockRecorder {
	return m.recorder
}

// DeploymentName mocks base method
func (m *MockDeployer) DeploymentName(arg0 string) string {
	ret := m.ctrl.Call(m, "DeploymentName", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// DeploymentName indicates an expected call of DeploymentName
func (mr *MockDeployerMockRecorder) DeploymentName(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeploymentName", reflect.TypeOf((*MockDeployer)(nil).DeploymentName), arg0)
}

// PodIPs mocks base method
func (m *MockDeployer) PodIPs(arg0 string) ([]net.IP, error) {
	ret := m.ctrl.Call(m, "PodIPs", arg0)
	ret0, _ := ret[0].([]net.IP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PodIPs indicates an expected call of PodIPs
func (mr *MockDeployerMockRecorder) PodIPs(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PodIPs", reflect.TypeOf((*MockDeployer)(nil).PodIPs), arg0)
}

// Scale mocks base method
func (m *MockDeployer) Scale(arg0 context.Context, arg1 string, arg2 uint) error {
	ret := m.ctrl.Call(m, "Scale", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scale indicates an expected call of Scale
func (mr *MockDeployerMockRecorder) Scale(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scale", reflect.TypeOf((*MockDeployer)(nil).Scale), arg0, arg1, arg2)
}
