FROM mbrt/distcc-ubuntu:latest

RUN apt update                    && \
    apt install -y openssh-server && \
    apt clean                     && \
    rm -rf /var/cache/apt

RUN mkdir /var/run/sshd                                                           && \
    adduser --disabled-password --gecos "" dev                                    && \
    sed -ri 's/^StrictModes\s+.*/StrictModes no/' /etc/ssh/sshd_config

ENTRYPOINT ["/tini", "--"]
CMD ["/usr/sbin/sshd", "-D"]
