// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mbrt/k8cc/pkg/controller (interfaces: Controller,TagController)

// Package mock_controller is a generated GoMock package.
package mock_controller

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	controller "github.com/mbrt/k8cc/pkg/controller"
	reflect "reflect"
	time "time"
)

// MockController is a mock of Controller interface
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// DoMaintenance mocks base method
func (m *MockController) DoMaintenance(arg0 context.Context, arg1 time.Time) {
	m.ctrl.Call(m, "DoMaintenance", arg0, arg1)
}

// DoMaintenance indicates an expected call of DoMaintenance
func (mr *MockControllerMockRecorder) DoMaintenance(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoMaintenance", reflect.TypeOf((*MockController)(nil).DoMaintenance), arg0, arg1)
}

// TagController mocks base method
func (m *MockController) TagController(arg0 string) controller.TagController {
	ret := m.ctrl.Call(m, "TagController", arg0)
	ret0, _ := ret[0].(controller.TagController)
	return ret0
}

// TagController indicates an expected call of TagController
func (mr *MockControllerMockRecorder) TagController(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagController", reflect.TypeOf((*MockController)(nil).TagController), arg0)
}

// MockTagController is a mock of TagController interface
type MockTagController struct {
	ctrl     *gomock.Controller
	recorder *MockTagControllerMockRecorder
}

// MockTagControllerMockRecorder is the mock recorder for MockTagController
type MockTagControllerMockRecorder struct {
	mock *MockTagController
}

// NewMockTagController creates a new mock instance
func NewMockTagController(ctrl *gomock.Controller) *MockTagController {
	mock := &MockTagController{ctrl: ctrl}
	mock.recorder = &MockTagControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTagController) EXPECT() *MockTagControllerMockRecorder {
	return m.recorder
}

// LeaseUser mocks base method
func (m *MockTagController) LeaseUser(arg0 context.Context, arg1 string, arg2 time.Time) (controller.Lease, error) {
	ret := m.ctrl.Call(m, "LeaseUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(controller.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LeaseUser indicates an expected call of LeaseUser
func (mr *MockTagControllerMockRecorder) LeaseUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaseUser", reflect.TypeOf((*MockTagController)(nil).LeaseUser), arg0, arg1, arg2)
}
